### ISSUE TITLE
Failed to load the linter-manager package

### ISSUE THREAD

**Issue by jitendravyas** [benjaminRomano/linter-manager#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-manager](https://github.com/benjaminRomano/linter-manager) package, v0.1.0
### Stack Trace

Failed to load the linter-manager package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/jitendra.vyas/.atom/packages/linter-manager/lib/views/linter-manager.coffee:4:5)
  at Object.<anonymous> (/Users/jitendra.vyas/.atom/packages/linter-manager/lib/views/linter-manager.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/jitendra.vyas/.atom/packages/linter-manager/lib/main.coffee:3:17)
  at Object.<anonymous> (/Users/jitendra.vyas/.atom/packages/linter-manager/lib/main.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:759:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:370:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -1:15.4.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
     -0:24.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.11
autoclose-html, v0.18.0
autocomplete-html-entities, v0.1.0
bottom-dock, v0.2.1
color-picker, v2.0.11
gulp-manager, v0.2.4
language-nunjucks, v2.0.0
linter-bootlint, v0.0.6
linter-manager, v0.1.0
minimap, v4.12.2

# Dev
No dev packages
```

**Comment by benjaminRomano** [comment]
I just made some bug fixes in 1ed7da2abd33cce21e6d46745a7bccb64f144f42. Can you verify that it works now? Thanks
