### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by gzamboni** [benjaminRomano/linter-manager#10]
[Enter steps to reproduce below:]
1. the lint-jade module found an error on my project (TypeError)
2. I just presses cmd+w

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-manager](https://github.com/benjaminRomano/linter-manager) package, v0.2.8
### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of null

```
At /Users/zamboni/.atom/packages/linter-manager/lib/views/linter-manager.coffee:110

TypeError: Cannot read property 'indexOf' of null
    at LinterManager.createRow (/Users/zamboni/.atom/packages/linter-manager/lib/views/linter-manager.coffee:110:35)
    at LinterManager.<anonymous> (/Users/zamboni/.atom/packages/linter-manager/lib/views/linter-manager.coffee:101:14)
    at LinterManager.renderMessages (/Users/zamboni/.atom/packages/linter-manager/lib/views/linter-manager.coffee:101:13)
    at LinterManager.render (/Users/zamboni/.atom/packages/linter-manager/lib/views/linter-manager.coffee:76:6)
    at LinterManager.render (/Users/zamboni/.atom/packages/linter-manager/lib/views/linter-manager.coffee:1:1)
    at /Users/zamboni/.atom/packages/linter-manager/lib/views/linter-manager.coffee:61:8
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/pane.js:312:19)
    at Pane.module.exports.Pane.activatePreviousItem (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/pane.js:277:21)
    at Pane.module.exports.Pane.removeItem (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/pane.js:402:16)
    at Pane.module.exports.Pane.destroyItem (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/pane.js:464:16)
    at Pane.module.exports.Pane.destroyActiveItem (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/pane.js:444:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/workspace.js:657:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/workspace.js:696:21)
    at atom-workspace.commandRegistry.add.core:close (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:170:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:16.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:14.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:00.8.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
  3x -0:56.6.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-atom-dark-ui)
     -0:33.3.0 build:trigger (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-atom-dark-ui)
     -0:19.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:17.7.0 core:close (atom-text-editor.editor.is-focused)
     -0:08.5.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-atom-dark-ui)
     -0:04.9.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "hideGitIgnoredFiles": true,
    "ignoredNames": [
      ".bundle",
      ".git",
      "log",
      "repositories",
      "tmp",
      "vendor"
    ],
    "projectHome": "~/Code",
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.4
atom-beautify, v0.28.22
atom-jade, v0.3.0
bottom-dock, v0.3.7
build, v0.55.0
build-gulp, v0.7.0
color-picker, v2.1.1
csslint, v1.1.4
editorconfig, v1.2.4
file-icons, v1.6.15
highlight-line, v0.11.1
jshint, v1.8.3
language-json, v0.17.4
language-rspec, v0.5.0
linter, v1.11.3
linter-bootlint, v1.0.0
linter-csslint, v1.3.1
linter-jade, v0.3.2
linter-jshint, v2.0.2
linter-jsonlint, v1.1.6
linter-less, v2.4.2
linter-manager, v0.2.8
linter-pylint, v1.2.0
linter-sass-lint, v1.1.1
linter-shellcheck, v1.1.0
minimap, v4.19.0
project-manager, v2.7.6

# Dev
No dev packages
```

**Comment by benjaminRomano** [comment]
Looks like linter-manager fails when linter messages don't have a file path associated with it.
It should be fixed now in v0.2.9.
