### ISSUE TITLE
Error on open Atom: Failed to activate the bottom-dock package

### ISSUE THREAD

**Issue by maximaexchen** [benjaminRomano/linter-manager#3]
Hi.
Just opend Atom.

Error message:

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10
**Thrown From**: [linter-manager](https://github.com/benjaminRomano/linter-manager) package, v0.2.2
### Stack Trace

Failed to activate the bottom-dock package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.consumeBottomDock (/Users/maximaexchen/.atom/packages/linter-manager/lib/main.coffee:100:46)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:417:65)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:246:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:312:60
```
### Commands

```
     -0:30.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
bottom-dock, v0.3.2
git-diff-details, v0.20.0
grunt-manager, v0.1.5
linter, v1.4.3
linter-manager, v0.2.2
project-manager, v1.15.11
todo-manager, v0.2.2

# Dev
No dev packages
```

**Comment by benjaminRomano** [comment]
Did you just update the packages? It might require a restart to work properly.

**Comment by maximaexchen** [comment]
Yes I did.
Restart did the trick.
Thanks
