### ISSUE TITLE
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by spdaly** [benjaminRomano/linter-manager#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-manager](https://github.com/benjaminRomano/linter-manager) package, v0.2.6
### Stack Trace

Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.

```
At /Users/spdaly/.atom/packages/linter-manager/node_modules/atom-bottom-dock/node_modules/bd-slickgrid/grid.js:1497

TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
  at TypeError (native)
  at removeRowFromCache (/Users/spdaly/.atom/packages/linter-manager/node_modules/atom-bottom-dock/node_modules/bd-slickgrid/grid.js:1497:18)
  at invalidateAllRows (/Users/spdaly/.atom/packages/linter-manager/node_modules/atom-bottom-dock/node_modules/bd-slickgrid/grid.js:1488:9)
  at SlickGrid.setData (/Users/spdaly/.atom/packages/linter-manager/node_modules/atom-bottom-dock/node_modules/bd-slickgrid/grid.js:1267:7)
  at TableView.deleteAllRows (/Users/spdaly/.atom/packages/linter-manager/node_modules/atom-bottom-dock/lib/table-view.coffee:32:11)
  at LinterManager.renderMessages (/Users/spdaly/.atom/packages/linter-manager/lib/views/linter-manager.coffee:95:12)
  at LinterManager.render (/Users/spdaly/.atom/packages/linter-manager/lib/views/linter-manager.coffee:73:6)
  at LinterManager.render (/Users/spdaly/.atom/packages/linter-manager/lib/views/linter-manager.coffee:1:1)
  at /Users/spdaly/.atom/packages/linter-manager/lib/views/linter-manager.coffee:58:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:247:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:311:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -0:34.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:31.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:30.7.0 application:new-file (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/spdaly/Projects",
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-ruby-on-rails",
      "language-toml",
      "metrics",
      "open-on-github",
      "package-generator",
      "styleguide",
      "welcome"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
angularjs, v0.3.3
angularjs-styleguide-snippets, v0.7.2
atom-beautify, v0.28.16
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
bottom-dock, v0.3.5
change-case, v0.6.0
color-picker, v2.0.13
emmet, v2.3.13
encoding-selector, v0.21.0
file-icons, v1.6.11
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-docker, v1.1.3
linter, v1.10.0
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
linter-manager, v0.2.6
linter-sass-lint, v0.4.1
minimap, v4.15.1
open-recent, v2.3.0
pdf-view, v0.34.0
pigments, v0.18.1
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by benjaminRomano** [comment]
Do you remember what you were dong that caused this error?

**Comment by spdaly** [comment]
I'm trying to recreate it to get you the information.  Here's what I can remember:
1. Two Atom windows each with 2-4 tabs open
2. One Atom window had a short HTML file. The second had a very long HTML file in one tab and a large JSON file in the other tab.
3. I was comparing the two HTML files deleting from the second one.

The crash happened when I tried to click onto the JSON file in the second instance.

Sorry if that is confusing. I was trying to get the problem recreated.

Steve
