### ISSUE TITLE
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by spdaly** [benjaminRomano/linter-manager#8]
[Enter steps to reproduce below:]
1. I downloaded an email template from Zurb http://foundation.zurb.com/downloads/templates-emails/hero.html
2. Opened it in Atom.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-manager](https://github.com/benjaminRomano/linter-manager) package, v0.2.6
### Stack Trace

Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

```
At /Users/spdaly/.atom/packages/linter-manager/node_modules/atom-bottom-dock/node_modules/bd-slickgrid/grid.js:1885

TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at TypeError (native)
    at renderRows (/Users/spdaly/.atom/packages/linter-manager/node_modules/atom-bottom-dock/node_modules/bd-slickgrid/grid.js:1885:49)
    at SlickGrid.render (/Users/spdaly/.atom/packages/linter-manager/node_modules/atom-bottom-dock/node_modules/bd-slickgrid/grid.js:1928:7)
    at TableView.addRows (/Users/spdaly/.atom/packages/linter-manager/node_modules/atom-bottom-dock/lib/table-view.coffee:27:11)
    at LinterManager.renderMessages (/Users/spdaly/.atom/packages/linter-manager/lib/views/linter-manager.coffee:99:12)
    at LinterManager.render (/Users/spdaly/.atom/packages/linter-manager/lib/views/linter-manager.coffee:73:6)
    at /Users/spdaly/.atom/packages/linter-manager/lib/views/linter-manager.coffee:1:1
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at MessageRegistry.updatePublic (/Users/spdaly/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/spdaly/.atom/packages/linter/lib/message-registry.js:24:16)
```
### Commands

```
     -0:52 application:new-file (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/spdaly/Projects",
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-ruby-on-rails",
      "language-toml",
      "metrics",
      "open-on-github",
      "package-generator",
      "styleguide",
      "welcome"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
angularjs-styleguide-snippets, v0.7.3
atom-ternjs, v0.10.3
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
bottom-dock, v0.3.5
color-picker, v2.0.14
emmet, v2.3.16
encoding-selector, v0.21.0
file-icons, v1.6.13
highlight-line, v0.11.0
highlight-selected, v0.11.1
linter, v1.11.3
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
linter-manager, v0.2.6
linter-sass-lint, v0.4.1
minimap, v4.16.2
open-recent, v4.0.1
pigments, v0.19.1
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by benjaminRomano** [comment]
I've not been able to reproduce the bug you mentioned.

However, I'm getting a bug where linter-htmllint errors and warnings aren't being displayed properly.
I'm assuming that this is the reason why atom is crashing for you. 

I'll fix this and hopefully it will solve your problem as well.

Here's a screenshot of what the messages are being displayed as
![image](https://cloud.githubusercontent.com/assets/9221137/11595687/4fb5684a-9a76-11e5-8704-1f774ec89b2b.png)

**Comment by benjaminRomano** [comment]
@spdaly I fixed html tags being displayed incorrectly in messages in v0.2.7.

Can you see if this stops the error message from appearing
